name: Test Branch Sweeping local git

on:
  workflow_dispatch:
    inputs:
      weeks_threshold:
        description: 'Number of weeks to consider a branch stale'
        required: true
        default: '4'
        type: number
      dry_run:
        description: 'Run in dry-run mode (no actual deletion)'
        required: true
        default: true
        type: boolean
      protected_branches:
        description: 'Space-separated list of protected branches'
        required: false
        default: 'release/**'
        type: string

jobs:
  test-sweeping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
        
      - name: Setup and run test
        run: |
          chmod +x ./branch-sweeper/tests/test-sweeping.sh
          cd ./branch-sweeper/tests
          ./test-sweeping.sh
      
      - name: Upload test summaries
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: branch-sweeper-test-results
          path: |
            ./branch-sweeper/tests/summary-*.md
          if-no-files-found: warn
          retention-days: 7
      
      - name: Post additional information to summary
        if: always()
        run: |
          echo "## Environment Information" >> $GITHUB_STEP_SUMMARY
          echo "- GitHub Runner: ${{ runner.os }}" >> $GITHUB_STEP_SUMMARY
          echo "- Git version: $(git --version)" >> $GITHUB_STEP_SUMMARY
          echo "- Repository: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "- Workflow: ${{ github.workflow }}" >> $GITHUB_STEP_SUMMARY